<pre>--- Summary ---
Tests passed: 1 out of 11

--- Details ---
Test #0: failed 
Test case description: World 1
TimeoutException: Exceeded time limit!

Test #1: failed 
Test case description: World 2
TimeoutException: Exceeded time limit!

Test #2: failed 
Test case description: World 4
TimeoutException: Exceeded time limit!

Test #3: failed 
Test case description: World 6
TimeoutException: Exceeded time limit!

Test #4: failed 
Test case description: World 7
TimeoutException: Exceeded time limit!

Test #5: failed 
Test case description: World 8
TimeoutException: Exceeded time limit!

Test #6: failed 
Test case description: World 9
TimeoutException: Exceeded time limit!

Test #7: failed 
Test case description: World 10
TimeoutException: Exceeded time limit!

Test #8: failed 
Test case description: World 1, dyna=200
TimeoutException: Exceeded time limit!

Test #9: failed 
Test case description: World 2, dyna=200
Traceback:
  File "/home/seb/gtFall2019/ML4T_2019Fall/grading/grading.py", line 114, in proc_wrapper
    rv['output'] = func(*pos_args,**keyword_args)
  File "/home/seb/gtFall2019/ML4T_2019Fall/qlearning_robot/grade_robot_qlearning.py", line 209, in timeoutwrapper_dyna
    return qltest(worldmap=world,iterations=50,max_steps=10000,learner=learner,verbose=False)
  File "/home/seb/gtFall2019/ML4T_2019Fall/qlearning_robot/grade_robot_qlearning.py", line 355, in qltest
    action = learner.querysetstate(state) #set the state and get first action
  File "/home/seb/gtFall2019/ML4T_2019Fall/qlearning_robot/QLearner.py", line 74, in querysetstate
    action = np.argmax(self.Q[s,])
TypeError: 'NoneType' object is not subscriptable

Test #10: passed 
</pre>
